# Generated by Django 3.0.8 on 2020-07-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sopa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_words', models.TextField()),
                ('soup', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_file', models.FileField(upload_to='sopas/lista/')),
                ('width', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35)], default=17)),
                ('height', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35)], default=29)),
                ('n_orientations', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=8)),
                ('font_size', models.IntegerField(default=90)),
                ('square_size', models.IntegerField(default=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SopaMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soup_image', models.ImageField(blank=True, null=True, upload_to='sopas/')),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='sopas/')),
                ('list_file', models.FileField(blank=True, null=True, upload_to='sopas/')),
                ('soup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='puzzleprinter.Sopa')),
            ],
        ),
        migrations.AddField(
            model_name='sopa',
            name='words_list_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzleprinter.WordsList'),
        ),
    ]
