# Generated by Django 3.0.8 on 2020-11-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzleprinter', '0002_wordslist_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordslist',
            name='fill',
            field=models.TextField(choices=[('Letras', 'Letras'), ('Números', 'Números')], default='Letras'),
        ),
    ]
